#Use the text to speech at all
useTTS = true
#Hide all Verity UI (and chat if the server host has this on)
immersiveMode = false
#The amount of in-game days before Verity turns hostile/demon.
dayCount = 5
#Allow Verity to kick you from the server.
canCrash = true
#Play the Verity Edit on the startup of the client.
playVideo = false
#Require 'Verity' in every sentence to speak to him.
requireVerity = false
#Use the OS's built-in narrator (Windows, macOS, Linux) instead of Groq cloud TTS.
useNativeTts = true
#The extreme darkness toggle
trueDarkness = true
#Toggles if Verity should kill villagers.
killVillagers = false
#Toggles the Karma bar above your hotbar.
showKarma = true

[AISettings]
	#Choose the voice Verity has
	voice = "Daniel"
	#Use the offline Kitten AI Voice instead of Groq cloud TTS.
	useLocalTts = false
	#Offline STT
	useLocalStt = false
	#Put your Groq API Key here to give Verity a brain.
	apiKey = ""
	#Choose the AI intelligence level.
	#Allowed Values: FAST_LITE, FAST, INTELLIGENT
	aiModel = "FAST"
	#Choose the AI Provider to use for Verity.
	#Allowed Values: GROQ, OPENROUTER
	aiProvider = "GROQ"
	#If true the mod will always use Ollama instead of an AI Provider.
	use_ollama = false
	#The URL of the LiteLLM Server.
	ollama_url = "http://127.0.0.1:4000/v1/"
	#The AI model the mod uses.
	ollama_ai_model = "ollama/qwen2.5:1.5b"
	#Toggels thinking mode for smarter or faster responsens. (Qwen3 Models only)
	thinking_mode = false
	#If true the mod will always use Kokoro TTS instead of an AI Provider or build in TTS.
	use_kokoro = false
	#The URL of the FastKokoro Server.
	ollama_tts_url = "http://127.0.0.1:8880/v1/"
	#The TTS model the mod uses.
	ollama_tts_model = "kokoro"
	#The voice Kokoro uses.
	ollama_tts_voice = "am_fenrir"
	#If true the mod will always use local STT instead of an AI Provider.
	use_local_whisper = false
	#The URL of the Whisper Server.
	ollama_stt_url = "http://127.0.0.1:9000/v1/"
	#The STT model the mod uses.
	ollama_stt_model = "models/ggml-large-v3-turbo.bin"

[Custom]
	#The Hue of Verity's texture color (0 to 360 degrees).
	#Range: 0 ~ 360
	colorHue = 0
	#The custom name for Verity. Leave empty to use default 'Verity'.
	customName = "Verity"
	#The custom personality for Verity.
	customPersonality = "normal"

